### ISSUE TITLE
[Calculator.koplugin]: Calculator stopped working. Bug in update check.

### ISSUE THREAD

**Issue by zwim** [koreader/contrib#10]
Information for all users of the `calculator` plugin:
**Please update to the latest version!** or delete the file `VERSION` in `/plugins/calculator.koplugin/`

There is a bug in the update check in 1.1.2 and 1.1.1: 
If there is a new version available and the file `VERSION` exists, those older two versions will not start (crash). 
The rest of KOReader is not affected.

**Comment by Hzj-jie** [comment]
Since the latest version is 1.1.4 now, can we close this bug?
